# Generated by Django 2.2.7 on 2019-12-14 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField(blank=True, null=True)),
                ('nombre_empresa', models.CharField(max_length=60)),
                ('tareas_principales', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Hobbie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
                ('telefono', models.CharField(max_length=16)),
                ('direccion', models.CharField(max_length=100)),
                ('resumen', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCapacitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_capacitacion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField(blank=True, null=True)),
                ('nombre_institucion', models.CharField(max_length=60)),
                ('titulo', models.CharField(max_length=60)),
                ('descripcion', models.CharField(max_length=500)),
                ('tipo_capacitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.TipoCapacitacion')),
            ],
        ),
    ]
