# Generated by Django 2.2.7 on 2019-12-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_auto_20191214_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitacion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
