# Generated by Django 2.2.7 on 2019-12-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_auto_20191214_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='instagram',
            field=models.URLField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='persona',
            name='linkedin',
            field=models.URLField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='persona',
            name='twitter',
            field=models.URLField(default='', max_length=100),
        ),
    ]
