# Generated by Django 2.2.7 on 2019-12-14 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_auto_20191214_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capacitacion',
            name='descripcion',
        ),
    ]
